CREATE DATABASE cars;
GRANT ALL PRIVILEGES ON DATABASE cars TO program;

CREATE DATABASE rentals;
GRANT ALL PRIVILEGES ON DATABASE rentals TO program;

CREATE DATABASE payments;
GRANT ALL PRIVILEGES ON DATABASE payments TO program;

CREATE DATABASE statistique;
GRANT ALL PRIVILEGES ON DATABASE payments TO program;

CREATE DATABASE user_db;
GRANT ALL PRIVILEGES ON DATABASE user_db TO program;