name: Build Project
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
env:
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  REGISTRY: "registry.digitalocean.com/rsoi-project"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v2
      - name: Build Images
        run: docker compose build
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: voir images
        run: docker images
      - name: Login to docker container registry
        run: doctl registry login --expiry-seconds 1200
      - name: Push Loyalty image in to Digital ocean Container Registry
        run: docker push registry.digitalocean.com/rsoi-project/loyaltyservice:latest
      - name: Push Payment image in to Digital ocean Container Registry
        run: docker push registry.digitalocean.com/rsoi-project/paymentservice:latest
      - name: Push Session image in to Digital ocean Container Registry
        run: docker push registry.digitalocean.com/rsoi-project/sessionservice:latest
      - name: Push Report image in to Digital ocean Container Registry
        run: docker push registry.digitalocean.com/rsoi-project/reportservice:latest
      - name: Push Reservation image in to Digital ocean Container Registry
        run: docker push registry.digitalocean.com/rsoi-project/reservationservice:latest
      - name: Push Gateway image in to Digital ocean Container Registry
        run: docker push registry.digitalocean.com/rsoi-project/gatewayservice:latest
      - name: k8s cluster kubeconfig
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 1200 cluster-rsoi-project
      - name: Deployment to the cluster
        run: |
          cd k8s
          kubectl delete -f load-Balancer.yaml
          helm upgrade --install postgres postgres-chart/
          helm upgrade --install services services-chart/
          kubectl apply -f load-Balancer.yaml
          sleep 120
